import 'package:flutter/material.dart';
import '../../core/models/scheme_model.dart';

class SchemeProvider extends ChangeNotifier {
  final List<SchemeModel> _schemes = [
    // FARMER
    SchemeModel(
      name: "PM Kisan Samman Nidhi",
      department: "Agriculture Ministry",
      description: "Income support of Rs 6000 per year in three equal installments to small and marginal farmer families.",
      minAge: 18,
      maxAge: 60,
      incomeLimit: 500000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Farmer"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Land Ownership Proof"],
      uploadDate: DateTime.now().subtract(const Duration(days: 1)),
      isNew: true,
      applyLink: "https://pmkisan.gov.in/",
    ),
    SchemeModel(
      name: "Pradhan Mantri Fasal Bima Yojana",
      department: "Agriculture Ministry",
      description: "Crop insurance scheme to provide financial support to farmers in case of crop failure due to natural calamities.",
      minAge: 18,
      maxAge: 60,
      incomeLimit: 600000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Farmer"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Land Records"],
      uploadDate: DateTime.now().subtract(const Duration(days: 2)),
      isNew: false,
      applyLink: "https://pmfby.gov.in/",
    ),
    // CORPORATE EMPLOYEE
    SchemeModel(
      name: "Employees State Insurance Scheme",
      department: "Labour Ministry",
      description: "Social security and health insurance for workers in the organized sector.",
      minAge: 18,
      maxAge: 60,
      incomeLimit: 500000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Corporate Employee"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Employment Certificate"],
      uploadDate: DateTime.now().subtract(const Duration(days: 3)),
      isNew: false,
      applyLink: "https://www.esic.nic.in/",
    ),
    SchemeModel(
      name: "Employees Provident Fund",
      department: "Labour Ministry",
      description: "Retirement savings scheme for salaried employees with employer contribution.",
      minAge: 18,
      maxAge: 60,
      incomeLimit: 800000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Corporate Employee"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "PAN Card"],
      uploadDate: DateTime.now().subtract(const Duration(days: 4)),
      isNew: false,
      applyLink: "https://www.epfindia.gov.in/",
    ),
    // DOCTOR
    SchemeModel(
      name: "Ayushman Bharat Health Professional Coverage",
      department: "Health Ministry",
      description: "Health insurance coverage for healthcare professionals and their families.",
      minAge: 18,
      maxAge: 60,
      incomeLimit: 800000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Doctor"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Medical Registration"],
      uploadDate: DateTime.now().subtract(const Duration(days: 5)),
      isNew: true,
      applyLink: "https://pmjay.gov.in/",
    ),
    SchemeModel(
      name: "National Health Mission Support Scheme",
      department: "Health Ministry",
      description: "Support for doctors and health professionals in rural and underserved areas.",
      minAge: 21,
      maxAge: 60,
      incomeLimit: 700000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Doctor"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Degree Certificate"],
      uploadDate: DateTime.now().subtract(const Duration(days: 6)),
      isNew: false,
      applyLink: "https://nhm.gov.in/",
    ),
    // STUDENT
    SchemeModel(
      name: "Prime Minister Scholarship Scheme",
      department: "Education Ministry",
      description: "Scholarship for wards of armed forces personnel and central paramilitary forces.",
      minAge: 18,
      maxAge: 25,
      incomeLimit: 300000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Student"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Income Certificate"],
      uploadDate: DateTime.now().subtract(const Duration(days: 7)),
      isNew: true,
      applyLink: "https://www.desw.gov.in/prime-ministers-scholarship-scheme-pmss",
    ),
    SchemeModel(
      name: "Post Matric Scholarship Portal",
      department: "Education Ministry",
      description: "Scholarship for SC, ST, OBC and minority students pursuing higher education.",
      minAge: 16,
      maxAge: 30,
      incomeLimit: 350000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Student"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Caste Certificate"],
      uploadDate: DateTime.now().subtract(const Duration(days: 8)),
      isNew: false,
      applyLink: "https://scholarships.gov.in/",
    ),
    // BUSINESS OWNER
    SchemeModel(
      name: "MSME Support Scheme",
      department: "MSME Ministry",
      description: "Credit, subsidy and support for micro, small and medium enterprises.",
      minAge: 21,
      maxAge: 60,
      incomeLimit: 800000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Business Owner"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Business Registration"],
      uploadDate: DateTime.now().subtract(const Duration(days: 9)),
      isNew: false,
      applyLink: "https://msme.gov.in/",
    ),
    SchemeModel(
      name: "Startup India Initiative",
      department: "Commerce Ministry",
      description: "Tax benefits, funding support and incubation for eligible startups.",
      minAge: 21,
      maxAge: 55,
      incomeLimit: 1000000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Business Owner"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Company Incorporation"],
      uploadDate: DateTime.now().subtract(const Duration(days: 10)),
      isNew: true,
      applyLink: "https://www.startupindia.gov.in/",
    ),
    // UNEMPLOYED
    SchemeModel(
      name: "Pradhan Mantri Kaushal Vikas Yojana",
      department: "Skill Development Ministry",
      description: "Short-term skill training to help unemployed youth gain industry-relevant skills.",
      minAge: 18,
      maxAge: 45,
      incomeLimit: 300000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Unemployed"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Income Certificate"],
      uploadDate: DateTime.now().subtract(const Duration(days: 11)),
      isNew: false,
      applyLink: "https://www.pmkvyofficial.org/",
    ),
    SchemeModel(
      name: "Atmanirbhar Bharat Rojgar Yojana",
      department: "Labour Ministry",
      description: "Wage subsidy for new employees to encourage job creation in formal sector.",
      minAge: 18,
      maxAge: 60,
      incomeLimit: 400000,
      eligibleCategories: ["General", "OBC", "SC", "ST"],
      eligibleStates: ["All"],
      eligibleOccupations: ["Unemployed"],
      eligibleGenders: ["Male", "Female"],
      requiredDocuments: ["Aadhar Card", "Employment Status Proof"],
      uploadDate: DateTime.now().subtract(const Duration(days: 12)),
      isNew: true,
      applyLink: "https://labour.gov.in/aatmanirbhar-bharat-rojgar-yojana-abry",
    ),
  ];

  List<SchemeModel> get schemes => _schemes;

  void addScheme(SchemeModel scheme) {
    _schemes.add(scheme);
    notifyListeners();
  }

  void deleteScheme(SchemeModel scheme) {
    _schemes.remove(scheme);
    notifyListeners();
  }
}
